# Generated by Django 5.2.4 on 2025-07-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=1000, verbose_name='Цитата')),
                ('likes', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Кол-во лайков')),
                ('film', models.CharField(max_length=50, verbose_name='Фильм')),
            ],
        ),
    ]
