# Generated by Django 5.2.4 on 2025-07-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='weight',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=3, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='citation',
            name='likes',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9, verbose_name='Кол-во лайков'),
        ),
    ]
