# Generated by Django 5.2.4 on 2025-07-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_citation_weight_alter_citation_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='weight',
            field=models.PositiveBigIntegerField(default=1, verbose_name='Вес'),
        ),
    ]
