# Generated by Django 5.2.4 on 2025-07-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_session_key_like_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
